# fly.toml app configuration file generated for penguin-image-classification-api on 2023-10-07T07:31:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "penguin-image-classification-api"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  ENV = "PRODUCTION"
  HOST = "0.0.0.0"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
