EXPERIMENTS:
  ver: 'r1'
  mlflow: 'penguin'
PREPARE:
  batch_size: 32
CNN:
  mode: 'penguin'
  seed: 42
  backborn: resnet34 # resnet mobilenet resnet34 efficientnet
  epoch: 30
  classification: 7
  checkpoint: 10
  lr: 0.0001
  weight_decay: 0.001
  dropout: 0.2 # default: 0.5 # 0.0 # 0.2
  hpo: True # True # False
  n_trials: 5 # HPO
  direction: 'minimize' # minimize # maximize
TARGETS:
  - Aptenodytes
  - Pygoscelis
  - Spheniscus
  - Eudyptes
  - Megadyptes
  - Eudyptula
  - Other
PATH:
  work: './'
  model: 'model'
  data: 'data/penguins'
MLFLOW:
  tracking_uri: 'http://mlflow-mlflo-wg8oqwixegkp-0c8c3c12eb9d84fe.elb.ap-northeast-1.amazonaws.com/'
  artifact_uri: 's3://mlflow-artifacts-953247918566/experiments'
