EXPERIMENTS:
  ver: 'r0'
  mlflow: 'penguin'
PREPARE:
  batch_size: 32
CNN:
  mode: 'penguin'
  seed: 42
  backborn: resnet34 # resnet mobilenet resnet34 efficientnet
  epoch: 50
  classification: 7
  checkpoint: 10
  lr: 0.0001
  weight_decay: 0.001
TARGETS:
  - Aptenodytes
  - Pygoscelis
  - Spheniscus
  - Eudyptes
  - Megadyptes
  - Eudyptula
  - Other
PATH:
  work: './'
  model: 'model'
  data: 'data/penguins'
