EXPERIMENTS:
  ver: 'r0'
  mlflow: 'penguin'
PREPARE:
  batch_size: 32
CNN:
  mode: 'penguin'
  seed: 42
  backborn: efficientnet # resnet mobilenet
  epoch: 3
  classification: 7
  checkpoint: 2
TARGETS:
  - Aptenodytes
  - Pygoscelis
  - Spheniscus
  - Eudyptes
  - Megadyptes
  - Eudyptula
  - Other
PATH:
  work: './'
  model: 'model'
  data: 'data/penguins'
