search_word: [
'コウテイペンギン',
'イワトビペンギン',
'ガラパゴスペンギン',
'キングペンギン',
'ハネジロペンギン',
'フンボルトペンギン',
'マゼランペンギン',
'ケープペンギン',
'コガタペンギン',
'ヒゲペンギン',
'フィヨルドランドペンギン',
'シュレーターペンギン',
'スネアーズペンギン',
'ロイヤルペンギン',
'マカロニペンギン',
'アデリーペンギン',
'ジェンツーペンギン',
'キンメペンギン',
]
